[
  %BeamDemo.Utils.StateCode{name: "Alabama", code: "AL"},
  %BeamDemo.Utils.StateCode{name: "Alaska", code: "AK"},
  %BeamDemo.Utils.StateCode{name: "Arizona", code: "AZ"},
  %BeamDemo.Utils.StateCode{name: "Arkansas", code: "AR"},
  %BeamDemo.Utils.StateCode{name: "California", code: "CA"},
  %BeamDemo.Utils.StateCode{name: "Colorado", code: "CO"},
  %BeamDemo.Utils.StateCode{name: "Connecticut", code: "CT"},
  %BeamDemo.Utils.StateCode{name: "Delaware", code: "DE"},
  %BeamDemo.Utils.StateCode{name: "Florida", code: "FL"},
  %BeamDemo.Utils.StateCode{name: "Georgia", code: "GA"},
  %BeamDemo.Utils.StateCode{name: "Idaho", code: "ID"},
  %BeamDemo.Utils.StateCode{name: "Illinois", code: "IL"},
  %BeamDemo.Utils.StateCode{name: "Indiana", code: "IN"},
  %BeamDemo.Utils.StateCode{name: "Iowa", code: "IA"},
  %BeamDemo.Utils.StateCode{name: "Kansas", code: "KS"},
  %BeamDemo.Utils.StateCode{name: "Kentucky", code: "KY"},
  %BeamDemo.Utils.StateCode{name: "Louisiana", code: "LA"},
  %BeamDemo.Utils.StateCode{name: "Maine", code: "ME"},
  %BeamDemo.Utils.StateCode{name: "Maryland", code: "MD"},
  %BeamDemo.Utils.StateCode{name: "Massachusetts", code: "MA"},
  %BeamDemo.Utils.StateCode{name: "Michigan", code: "MI"},
  %BeamDemo.Utils.StateCode{name: "Minnesota", code: "MN"},
  %BeamDemo.Utils.StateCode{name: "Mississippi", code: "MS"},
  %BeamDemo.Utils.StateCode{name: "Missouri", code: "MO"},
  %BeamDemo.Utils.StateCode{name: "Montana", code: "MT"},
  %BeamDemo.Utils.StateCode{name: "Nebraska", code: "NE"},
  %BeamDemo.Utils.StateCode{name: "Hampshire", code: "NH"},
  %BeamDemo.Utils.StateCode{name: "New Jersey", code: "NJ"},
  %BeamDemo.Utils.StateCode{name: "New Mexico", code: "NM"},
  %BeamDemo.Utils.StateCode{name: "New York", code: "NY"},
  %BeamDemo.Utils.StateCode{name: "North Carolina", code: "NC"},
  %BeamDemo.Utils.StateCode{name: "North Dakota", code: "ND"},
  %BeamDemo.Utils.StateCode{name: "Ohio", code: "OH"},
  %BeamDemo.Utils.StateCode{name: "Oklahoma", code: "OK"},
  %BeamDemo.Utils.StateCode{name: "Oregon", code: "OR"},
  %BeamDemo.Utils.StateCode{name: "Pennsylvania", code: "PA"},
  %BeamDemo.Utils.StateCode{name: "Rhode Island", code: "RI"},
  %BeamDemo.Utils.StateCode{name: "South Carolina", code: "SC"},
  %BeamDemo.Utils.StateCode{name: "South Dakota", code: "SD"},
  %BeamDemo.Utils.StateCode{name: "Tennessee", code: "TN"},
  %BeamDemo.Utils.StateCode{name: "Texas", code: "TX"},
  %BeamDemo.Utils.StateCode{name: "Utah", code: "UT"},
  %BeamDemo.Utils.StateCode{name: "Vermont", code: "VT"},
  %BeamDemo.Utils.StateCode{name: "Virginia", code: "VA"},
  %BeamDemo.Utils.StateCode{name: "Washington", code: "WA"},
  %BeamDemo.Utils.StateCode{name: "West Virginia", code: "WV"},
  %BeamDemo.Utils.StateCode{name: "Wisconsin", code: "WI"},
  %BeamDemo.Utils.StateCode{name: "Wyoming", code: "WY"}
]